before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DuXC+9n0cxyXamSrtSnPQWnKerkvBvCkgkh64EPnEjAzgqEVC8yeE+tGoBcAegjDoxMlQaP3TeLAJZ7XkaITVU1g2bt+BaIkp2gDwvCQ50kLtOBSb/3uwOQ/K+2ZQshjZ+bb7wKobhIV6IigKeoZt0zdyBq1tUsv8lkJy1TLSymFGq7ms2zVaOgJXMMHq4dlxgCXlA6qsrtcXb/x4YNg//eDn5Rw7U3y0fVsjssa3LE7sh3PsS/GJf78znHnRkZKRq4j+Dpx9pce9WTz+LkVUqAT+FX6Gx6CXQd7nO8LbfUWdeWOfjr69x/s0QEI9kWKgjKrEAvFMYpyPoa8mrFIBiNJCO/opUonl1Yv3skwFwAif37AexU8/+4C1JhblfQOIpBInoUw1TieG5WVFFYBH29JE8Z8UTS1qMvo9b2+LGc0Yo4JHSvnnRUO8SAq2ikQ7LzCmSx/UM6YZz4JaK+sQKxXyWdnar67KU7inRZacs+hHRF6RiIMsepg+o8F62NUKpSRp1hj12g2uSUZ1NJAc+yzjyNX6Y1NErR4yqtlfM0+dKjgRsKrHdTitljHKryTGLwyikeBpXSgjR+SaMI57FAW5r83VYKiMIABCmqIoadhttesMC+Q3wCNfWR956y04e5ymUrEjhhj+nqOkb1BBJ4HbB31zPurubh6n/eLi5Q= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
